language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
  - clang

sudo: required

before_install:
    - sudo apt-get install libsdl2-2.0-0
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libglew2.0
    - sudo apt-get install libglew-dev
    - sudo apt-get install glew-utils
#    - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz -O SDL2-2.0.7.tar.gz
#    - tar -xzvf SDL2-2.0.7.tar.gz


#install:
#    - "(cd SDL2-2.0.7 && ./configure && make && sudo make install)"

script:
  - chmod 777 test.sh
  - ./test.sh